name: Update RomPatcher.js Release

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 2 * * *' # Daily at 02:00 UTC

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.PAT }}
    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Get latest upstream release
      - name: Get latest upstream release
        id: set_version
        run: |
          # Fetch latest upstream release tag
          LATEST=$(curl -s https://api.github.com/repos/marcrobledo/RomPatcher.js/releases/latest | jq -r '.tag_name')
          echo "Latest upstream tag: $LATEST"

          # Get last built version from VERSION file
          if [ -f "VERSION" ]; then
            LAST=$(cat VERSION)
          else
            LAST=""
          fi
          echo "Last built version: $LAST"

          # Compare versions
          if [ "$LATEST" != "$LAST" ]; then
            echo "New version detected: $LATEST"
            echo "VERSION=$LATEST" >> $GITHUB_ENV
            echo "IS_NEW=true" >> $GITHUB_ENV
          else
            echo "No new version available."
            echo "VERSION=$LATEST" >> $GITHUB_ENV
            echo "IS_NEW=false" >> $GITHUB_ENV

      # 3. Update README.md and VERSION file if new version
      - name: Update README.md
        if: env.IS_NEW == 'true'
        run: |
          chmod +x ./scripts/update-readme.sh
          ./scripts/update-readme.sh ${{ env.VERSION }}

      # 4. Commit README and VERSION updates
      - name: Commit README and VERSION updates
        if: env.IS_NEW == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md VERSION
          git commit -m "chore: update README and VERSION to ${{ env.VERSION }}" || echo "No changes"
          git remote set-url origin https://xstar97:${GH_PAT}@github.com/xstar97/rompatcherjs.git
          git push origin main

      # 5. Tag the repo if the tag does not exist
      - name: Tag repo
        if: env.IS_NEW == 'true'
        run: |
          git remote set-url origin https://xstar97:${GH_PAT}@github.com/xstar97/rompatcherjs.git
          if git rev-parse "${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "Tag ${{ env.VERSION }} already exists. Skipping."
          else
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git tag ${{ env.VERSION }}
            git push origin ${{ env.VERSION }}

      # 6. Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 7. Build and push Docker image
      - name: Build and push Docker image
        if: env.IS_NEW == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/xstar97/rompatcherjs:${{ env.VERSION }}
            ghcr.io/xstar97/rompatcherjs:latest
          build-args: UPSTREAM_TAG=${{ env.VERSION }}
