name: Check RomPatcher.js Upstream Release

on:
  schedule:
    - cron: '0 2 * * *' # Daily at 02:00 UTC
  workflow_dispatch:

jobs:
  check-and-update:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository with token
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Automatically allows pushes

      # 2. Fetch latest upstream release tag (KEEP THIS BLOCK EXACTLY)
      - name: Get latest upstream release
        id: set_version
        run: |
          # Fetch latest upstream release tag
          LATEST=$(curl -s https://api.github.com/repos/marcrobledo/RomPatcher.js/releases/latest | jq -r '.tag_name')
          echo "Latest upstream tag: $LATEST"
          
          # Get last built version from VERSION file
          if [ -f "VERSION" ]; then
            LAST=$(cat VERSION)
          else
            LAST=""
          fi
          echo "Last built version: $LAST"
          
          # Compare versions
          if [ "$LATEST" != "$LAST" ]; then
            echo "New version detected: $LATEST"
            echo "VERSION=$LATEST" >> $GITHUB_ENV
            echo "IS_NEW=true" >> $GITHUB_ENV
          else
            echo "No new version available."
            echo "VERSION=$LATEST" >> $GITHUB_ENV
            echo "IS_NEW=false" >> $GITHUB_ENV
          fi

      # 3. Update README.md if new version
      - name: Update README.md
        if: env.IS_NEW == 'true'
        run: |
          chmod +x ./scripts/update-readme.sh
          ./scripts/update-readme.sh $VERSION

      # 4. Commit README and VERSION update if new version
      - name: Commit README and VERSION update
        if: env.IS_NEW == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md VERSION
          git commit -m "chore: update README and VERSION to $VERSION" || echo "No changes"
          git push origin main

      # 5. Tag the repo if new version
      - name: Tag repo
        if: env.IS_NEW == 'true'
        run: |
          if git rev-parse "$VERSION" >/dev/null 2>&1; then
            echo "Tag $VERSION already exists. Skipping."
          else
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git tag $VERSION
            git push origin $VERSION
