name: Check RomPatcher.js Upstream Release

on:
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Get latest upstream release
      - name: Get latest upstream release
        id: set_version
        run: |
          LATEST=$(curl -s https://api.github.com/repos/marcrobledo/RomPatcher.js/releases/latest | jq -r '.tag_name')
          echo "Latest upstream tag: $LATEST"

          if [ -f VERSION ]; then
            LAST=$(cat VERSION)
          else
            LAST=""
          fi
          echo "Last built version: $LAST"

          if [ "$LATEST" != "$LAST" ]; then
            echo "New version detected: $LATEST"
            echo "version=$LATEST" >> $GITHUB_OUTPUT
            echo "is_new=true" >> $GITHUB_OUTPUT
          else
            echo "No new version available."
            echo "version=$LATEST" >> $GITHUB_OUTPUT
            echo "is_new=false" >> $GITHUB_OUTPUT

      # 3. Trigger Docker build workflow if new version exists
      - name: Trigger docker-image workflow
        if: steps.set_version.outputs.is_new == 'true'
        uses: peter-evans/workflow-dispatch@v2
        with:
          token: ${{ secrets.PAT }}                # must be a PAT with repo & workflow permissions
          repository: ${{ github.repository }}
          workflow: docker-image.yml
          ref: main
          inputs: |
            version=${{ steps.set_version.outputs.version }}
