name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set version from tag
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update README.md
        run: ./scripts/update-readme.sh $VERSION

      - name: Commit README update
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "chore: update README to $VERSION" || echo "No changes"
          git push
