name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update README (required if manual)'
        required: false
  push:
    tags:
      - "v*.*.*"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch latest tag
        id: fetch_tag
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/xstar97/rompatcherjs/tags | jq -r '.[0].name')
          echo "Latest tag: $latest_tag"
          echo "VERSION=$latest_tag" >> $GITHUB_ENV

      - name: Update README.md
        run: bash ./scripts/update-readme.sh $VERSION

      - name: Commit README update
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "chore: update README to $VERSION" || echo "No changes"
          git push
